version: 2.1

orbs:
  python: circleci/python:3.7

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          python3 -m venv env
          . env/bin/activate
          pip install -r requirements.txt
      - run:
        name: run tests
        command: |
          . env/bin/activate
          flake8 src --statistics
          pytest -v --cov src

workflows:
  main:
    jobs:
      - build-and-test
